"""
ClassOS — Face Embedding Model
Stores 128-dimensional face embeddings generated by face_recognition.
"""

import uuid

from sqlalchemy import ForeignKey, Integer, LargeBinary, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database.base import Base, UUIDMixin, TimestampMixin


class FaceEmbedding(Base, UUIDMixin, TimestampMixin):
    """A single face sample embedding for a student."""

    __tablename__ = "face_embeddings"

    student_id: Mapped["uuid.UUID"] = mapped_column(
        UUID(as_uuid=True), ForeignKey("students.id", ondelete="CASCADE"),
        nullable=False, index=True
    )
    # Stored as raw bytes for efficiency (128 floats = 512 bytes)
    embedding: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    image_path: Mapped[str | None] = mapped_column(
        String(500), nullable=True,
        comment="Path to original captured face image"
    )
    sample_number: Mapped[int] = mapped_column(
        Integer, nullable=False,
        comment="Sample ID (1 to 20)"
    )

    # ----- Relationships -----
    student = relationship("Student", back_populates="face_embeddings")

    def __repr__(self) -> str:
        return f"<FaceEmbedding Student:{self.student_id} Sample:{self.sample_number}>"
